### ISSUE TITLE
fused lasso + trend filtering not working with Julia v 0.3.6 (2015-01-08 22:33 UTC) x86-64-linux-gnu

### ISSUE THREAD

**Issue by nrs02004** [simonster/Lasso.jl#1]
Very nice package!

Unfortunately I'm getting an error when trying to run fused lasso or trend filtering (LassoPath works like a charm):

Example code:

>using Lasso
>n = 100;
>p = 10000;
>X = rand(n,p) - 0.5;
>y = rand(n) - 0.5;
>lambda = norm(X'*y, Inf)/2
>f = fit(LassoPath, X,y);

>fit(FusedLasso, y, lambda)
ERROR: FusedLasso not defined

>fit(TrendFilter, y, 0, lambda)
ERROR: TrendFilter not defined

I apologize in advance if I'm doing something silly! (I'm still finding my sea-legs with Julia)

**Comment by simonster** [comment]
Fused lasso and trend filtering were documented but not yet available in a released version. I've just pushed a new release, so if you run `Pkg.update()` this should work.
