### ISSUE TITLE
not loading with julia 0.5

### ISSUE THREAD

**Issue by jotwin** [simonster/Lasso.jl#7]
> using Lasso
> ERROR: LoadError: UndefVarError: wrkwt! not defined
>  in include_from_node1(::String) at ./loading.jl:488
>  in eval(::Module, ::Any) at ./boot.jl:234
>  in require(::Symbol) at ./loading.jl:415
> while loading /home/jakub/.julia/v0.5/Lasso/src/Lasso.jl, in expression starting on line 18

**Comment by simonster** [comment]
GLM.jl was changed and this package needs to be tweaked to handle that change. I'm pretty busy right now but will try to take a look this weekend. Alternatively, you can roll back GLM.jl to a previous version.

**Comment by simonster** [comment]
Finally fixed.
